%% MXB103 Project Group 69:  BUNGEE!

%% 1  Introduction
% As part of Brisbane's "New World City" transformation, the Brisbane City
% Council is investigating a proposal to allow bungee jumping off the
% Story Bridge. This report addresses several key questions about the
% proposal.
%
% In Section 2 of this report, the proposal and the key questions relating 
% to it are discussed in more detail.  In Section 3, the model ...
% In Section 4, etc.

%% 2  The proposal
% The proposal calls for a platform to be installed at the very top of the
% Story Bridge, from which the bungee jumps will take place.
%
% Firstly, we have been asked to implement a second order or higher numerical 
% method to model the bungee jump. The code that we have chosen will obtain the numerical
% solution for the model and the bungee jumper's position will be plotted
% against time. 
%
% Secondly, we are then asked to observe the results of our model and
% determine whether it agrees with the bungee jump company's suggestion
% that a standard jump will consist of 10 "bounces" which should take
% approximately 60 seconds. 
%
% Thirdly, the maximum speed of the bungee jumper and when it occurs in 
% relation to the overall jump need to be determined. It asks us to 
% graphically plot the jumper's velocity against time.
%
% Fourthly, in order to solve the following question, numerical differentiation
% must be used to find the acceleration predicted by our model. After that,
% we have to plot the jumper's acceleration against time. 
% 
% Fifthly, we are then asked to compute the integral to determine how far the jumper
% actually travels in the 60 second jump. To compute the integral numerical
% integration will be used. 
% 
% Sixthly, a constituent of the proposal is to install a camera on the
% bridge deck at height D from the water. An accurate value for t needs to be computed such that 
% y(t) = H - D.
%
% Lastly, the bungee company then asks us to determine how close the jumper is to
% touch the water. An investigation into how the bungee rope could be
% altered to produce an accurate experience of a water touch for a jumper
% who weighs 80kg, while still maintaing 10 bounces in 60 seconds.
%
% These questions that are asked will be answered in order as they are all
% related to each other. This way answers will be accurate. This approach
% will work well as it ensures that the questions are answered accordingly.
% 
% The next section will discuss the model in more detail, relating to the
% equation and its origin. 
%


%% 3 The model
%
% The equation of motion for bungee jumping is
%
% $\frac{dv}{dt} = g - C|v|v - max(0,K(y-L))$
% 
% Being aware of the forces (gravity (mg), drag(-c|v|v) and tension 
% (-max(0,k(y-L))) that are regularly acting on the jumper, the mathematical 
% model of performing bungee jumping can be derived. 
% 
% The sum of the forces that are acting on the jumper equals the product of
% the jumper's mass and acceleration. The ODE which governs bungee jumping
% is
% 
% $\frac m{dv}{dt} = mg - c|v|v - max(0,k(y-L))$
%
% The drag force acts in the opposite direction to motion which always 
% slows the jumper down. The value is given by -c|v|v, c is the drag 
% coefficient and the velocity of the jumper is v. The length of the 
% unstretched rope is L, the tension when the rope is
% taut is k(y-L), where the "spring constant" k measures the bungee ropes
% elasticity. The tension force is - max(0,k(y-L)). When y > L the maximum
% function makes sure that the tension "switches on". And to make sure that
% it acts upwards the minus sign is placed in front. 
% 
% The equation of motion however, is a simplified version by dividing
% through m. Where C = c/m and K = k/m.
%

%% 3.1 Assumptions and limitations
%
% There are a few assumptions and limitations of the given model written in this project. 
% First of all, it is assumed that it is valid that the parameters of the model of the factors of 
% the bridge are given by the bungee jump company. Secondly, it is assumed for the Story Bridge that 
% the point in which jumping platform is set up is capable of sustaining the weight of platform and staffs on it.
% In terms of limitations of the given model, the only case of 80 kilograms jumper is considered as the result 
% generated from the model. What is more, there is a possibility that the expected result generated by 
% the model is different from the actual outcome of the jumping as the given model is a numerical solution.
%
% There exist some limitations in these solutions after the case study
% conducted. First of all, this investigation ignores the case of rising tide. Therefore,
% the occurrence of 'water touch' would not exist in reality for a certain time.
% Moreover, this analysis ignores the case of ships moving under the bridge. Hence
% it is expected that the safety of the bungee jump is significantly low. On top of that, due to the weight of
% jumper and variables such as drag coefficient will not always be the same as
% given parameters, the actual situation of jumping may be variable according to the
% current situation.


%% 3.2 Parameters
H = 74;             % Height of jump point (m)
D = 31;             % Deck height (m)
c = 0.9;            % Drag coefficient (kg/m)
m = 80;             % Mass of the jumper (kg)
L = 25;             % Length of bungee cord (m)
k = 90;             % Spring constant of bungee cord (N/m)
g = 9.8;            % Gravitational acceleration (m/s^2)
C = c/m;            % Scaled drag coefficient
K = k/m;            % Scaled spring constant

%% 4 The numerical method
%
% Solving the bungee jumping equation will require just a slight modification of 
% numerical methods for solving ODEs that we have developed in our lectures.
% Because the equation of motion for bungee jumping involves two unknowns, v and y, a second
% equation is needed to relate the the two. The relationship is quite
% simple such that the jumper's velocity v is the derivative of the jumpers
% position y. This problem can be considered as two ODEs. 
% 
% $\frac{dy}{dt} = v$
% 
% $\frac{dv}{dt} = g - C|v|v - max(0,K(y-L))$
% 
% Any numerical method can now be applied to these two equations.
%

%% 4.1 Parameters

T = 60;             % Final time in simulation (s)
n = 10000;          % Number of subintervals (you decide how many you need)

%% 4.2 Solution
%
% The ordinary differential equations are solved using the Classical Fourth Order Runge-Kutta method.
[t, y, v, h] = rk4_bungee(T, n, g, C, K, L);

figure
plot(t, y);
xlabel('time (s)');
ylabel('distance fallen (m)');
title('Figure 1: Distance between Jumper and Platform.');

%% 5 Analysis
%
% In this section, the model predictions are analysed with respect to the
% key questions being asked about the proposal.
%

%% 5.1 Timing and bounces
%
% The bungee jump company suggests that the standard jump will consist of
% 10 "bounces" which should take approximately 60 seconds.
% Our model, Figure 1, does agree with the timing.
% 

%% 5.2 Maximum speed experienced by the jumper
%
% The "thrill factor" of bungee jumping is partly determined by the maximum
% speed experienced by the jumper.
%
% We can find the maximum velocity by:
[t, y, v, h] = rk4_bungee(T, n, g, C, K, L);

figure
plot(t,v);
xlabel('time (s)');
ylabel('velocity (m/s)');
title('Figure 2: Velocity of Jumper Vs Time');

% According to the graph, it seems that the maximum velocity achieved by
% the jumper is approximately 20 m/s.

%% 5.3 Maximum acceleration experienced by the jumper
%
% Another factor for thrill-seekers is the maximum acceleration experienced
% by the jumper. More acceleration equals bigger thrills, 
% however too much acceleration may be dangerous. Using numerical
% differentiation, the acceleration can be predicted by it.
%
% Therefore the maximum accleration can be determined by

[a, ~] = maximum_acceleration_bungee(v,h,n);

figure 
plot(t,abs(a));
xlabel('Time(Seconds)');
ylabel('Acceleration of Jumper(m/s/s)');
title('Figure 3: Jumpers Acceleration against Time');

%%
% According to the graph, the maximum acceleration experienced by the jumper
% occurs at approximately 4 seconds. Also, the jumper will be able to experience a maximum
% accleration of 18.3366m/s/s. What is more, the claim of "up to 2g"
% acceleration is not supported by the model.
% 

%% 5.4 Distance travelled by the jumper
%
% It is of interest to know how far the jumper actually travels in 
% the 60 second jump. Using numerical integration, the answer to this question
% can be computed to determine how far the jumper travels. 
%
% Therefore the distance travelled by the jumper is determined by

[t, y, ~, ~, x] = rk_bungee_integral(T, n, g, C, K, L);

figure
plot(t,x);
xlabel('Time(s)');
ylabel('Distance(m)');
title('Figure 4: Distance of jumper travelled');

%% 5.5 Automated camera system
%
% Describe the question, and then answer it.  In this case, you will
% fit an interpolating polynomial through the four points in your solution
% $y$ that lie either side of the camera location.  Then use that
% polynomial to solve for when the jumper passes the camera.

%% 5.6 Water touch option
%
% Describe the question, and then answer it.  In this case, you will
% re-solve the equations with different parameters for $L$ and $k$.  
% Experiment to find which values work best for the water touch option, but 
% include only the best combination that you found in the submitted code.

%% 6 Conclusion
%
% We are able to analyse different views of the bungee jump in order to meet the requirements
% of the bungee jump company with the Classical Fourth Runge-Kutta method which has been used to model the bungee jump.
% What the bungee company suggest is answered in order. The answers to question 1 and 2 use numerical solutions. 
% Also, numerical differentiation and integration are used to solve the question 3 and 4.
%
% The numerical solution and analysis for questions1, question2, question3, and question4
% are well presented in this document. However, one of our team members (Saint) does not participate in 
% this project, therefore, the numerical solution and analysis for question 5 and 6 are not
% presented at all. Due to the fact that the answers are based on the numerical model, further 
% investigation and more accurate solution, such as analytical solution and
% real field experiment on the Story Bridge, are highly recommended if
% the bungee jump company are still interested in this project.
%%